### ISSUE TITLE
Implement Feedback Collection System for AI-Human Interactions

### ISSUE THREAD

**Issue by JerryYang666** [os-computational-economics/ai4edu-api-service#59]
**Description:**

We need to design and implement a feedback collection system for our AI-human interaction platform, specifically for messages generated by large language models like ChatGPT. This system will allow users to provide feedback on AI responses in various formats, including:

- **Positive or negative feedback** (e.g., thumbs up/down), represented by ratings of `1` (positive) and `0` (negative).
- **Numerical ratings on different scales**:
  - Scale of `1` to `5`.
  - Scale of `1` to `10`.

Given that feedback submission is not expected to be a frequently used functionality, we will store this data in a regular SQL database (PostgreSQL) as SQL records.

**Updates to Requirements:**

- **Rating Values:**
  - For positive/negative feedback, ratings will be represented by `0` (negative) and `1` (positive).
  - **Remove the constraint that the rating cannot be zero**, as `0` is valid for negative feedback.
  
- **Feedback Target:**
  - Users can provide feedback for either a **single message** or an **entire thread** of messages.
  - There will be two fields to accommodate this:
    - `thread_id` (**NOT NULL**): Identifier of the thread being rated.
    - `message_id` (optional): Identifier of the specific message being rated.
      - If feedback is for a specific message, both `message_id` and `thread_id` are provided.
      - If feedback is for the entire thread, only `thread_id` is provided, and `message_id` is `NULL`.

**Objectives:**

- **Create a PostgreSQL table** to store feedback data with all necessary fields.
- **Support multiple rating formats**, allowing flexibility in how users provide feedback.
- **Allow feedback on either a single message or an entire thread**.
- **Ensure data integrity** and consistency across different feedback types.

**Database Schema Requirements:**

- **Table Name:** `feedback`

- **Fields:**
  - `feedback_id`:
    - Type: `SERIAL PRIMARY KEY`
    - Description: Auto-incrementing unique identifier for each feedback entry.
  - `thread_id`:
    - Type: `VARCHAR(32)` **NOT NULL**
    - Description: Unique identifier for the thread being rated.
  - `message_id` (optional):
    - Type: `VARCHAR(32)`
    - Description: Unique identifier for the message being rated.
    - Note: If feedback is for a specific message, `message_id` is provided along with `thread_id`. If feedback is for the entire thread, `message_id` is `NULL`.
  - `user_id`:
    - Type: `VARCHAR(64)` **NOT NULL**
    - Description: Identifier of the user providing the feedback.
  - `rating`:
    - Type: `INT` **NOT NULL**
    - Description: Numerical rating given by the user, which can be `0` or a positive integer depending on the rating format.
  - `rating_format`:
    - Type: `VARCHAR(16)` **NOT NULL**
    - Description: Indicates the rating scale or format (e.g., `"positive/negative"`, `"1-5"`, `"1-10"`).
  - `feedback_time`:
    - Type: `TIMESTAMPTZ` DEFAULT `CURRENT_TIMESTAMP`
    - Description: Timestamp of when the feedback was submitted.
  - `comments` (optional):
    - Type: `TEXT`
    - Description: Any additional comments or feedback from the user.

- **Constraints:**
  - **Rating Validity:**
    - Ensure that the `rating` value is appropriate for the specified `rating_format`.
    - For `"positive/negative"`, `rating` must be `0` or `1`.
    - For `"1-5"`, `rating` must be between `1` and `5`.
    - For `"1-10"`, `rating` must be between `1` and `10`.

**Example DDL:**

```sql
CREATE TABLE feedback (
    feedback_id SERIAL PRIMARY KEY,
    thread_id VARCHAR(32) NOT NULL,
    message_id VARCHAR(32),
    user_id VARCHAR(64) NOT NULL,
    rating INT NOT NULL,
    rating_format VARCHAR(16) NOT NULL,
    feedback_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    comments TEXT,
    CONSTRAINT chk_rating_validity CHECK (
        (rating_format = 'pn' AND rating IN (0, 1)) OR
        (rating_format = '1-5' AND rating BETWEEN 1 AND 5) OR
        (rating_format = '1-10' AND rating BETWEEN 1 AND 10)
    )
);
```

**Explanation of Fields and Constraints:**

- **feedback_id**: An auto-incrementing primary key for the feedback table.
- **thread_id**: Stores the ID of the thread being rated. This field is **NOT NULL** because feedback must be associated with a thread.
- **message_id**: (Optional) Stores the ID of the specific message being rated. If feedback is for the entire thread, this field is `NULL`.
- **user_id**: Represents the ID of the user providing the feedback.
- **rating**: Stores the numerical rating given by the user. The acceptable values depend on the `rating_format`.
- **rating_format**: Indicates the rating scale or format used.
- **feedback_time**: Stores the timestamp of when the feedback was created, defaulting to the current timestamp.
- **comments**: Allows optional user comments on the feedback.

**Constraints:**

- **chk_rating_validity**: Ensures that the `rating` value is valid for the specified `rating_format` by checking:
  - If `rating_format` is `'pn'`, `rating` must be `0` or `1`.
  - If `rating_format` is `'1-5'`, `rating` must be between `1` and `5`.
  - If `rating_format` is `'1-10'`, `rating` must be between `1` and `10`.

**Tasks:**

- [x] **Design the Database Schema:**

   - Define all necessary fields and data types as per the updated requirements.
   - Include appropriate constraints to ensure data validity.

- [x] **Implement the Feedback Table in PostgreSQL:**
   - Write the DDL statements to create the table.
   - Ensure the table is optimized for the expected volume of data.

- [ ] **Build API Endpoints:**
   - Develop API endpoints to allow front-end applications to submit feedback.
   - Validate incoming data to match the expected formats and scales.
